# Generated by Django 4.2.6 on 2023-10-11 05:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('objects', '0002_groupmodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('study_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subjects.teachermodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='disciplinemodel',
            constraint=models.UniqueConstraint(fields=('teacher', 'title'), name='teacher_title'),
        ),
    ]
