# Generated by Django 4.2.6 on 2023-10-11 05:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_studentmodel'),
        ('objects', '0003_disciplinemodel_disciplinemodel_teacher_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work', models.JSONField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_set', to='objects.disciplinemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='work_set', to='subjects.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('grade_date_time', models.DateTimeField()),
                ('grade_description', models.TextField()),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estimate_set', to='objects.workmodel')),
            ],
        ),
    ]
