# Generated by Django 4.2.6 on 2023-10-12 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_workmodel_estimatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
