# Generated by Django 4.2.6 on 2023-10-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_studentmodel'),
        ('objects', '0005_alter_groupmodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='group_set', to='subjects.teachermodel'),
        ),
    ]
