# Generated by Django 4.2.6 on 2023-10-13 05:38

from django.db import migrations, models
import objects.models.work_model


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_groupmodel_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='item_data',
            field=models.FileField(blank=True, help_text='DCM-data', null=True, upload_to=objects.models.work_model.WorkModel._work_path_),
        ),
    ]
