# Generated by Django 4.2.6 on 2023-10-13 05:41

from django.db import migrations, models
import objects.models.work_model


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_workmodel_item_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workmodel',
            old_name='work',
            new_name='item_meta',
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='item_data',
            field=models.FileField(blank=True, help_text='Excel-file', null=True, upload_to=objects.models.work_model.WorkModel._work_path_),
        ),
    ]
