# Generated by Django 4.2.6 on 2023-10-15 04:19

import django.core.validators
from django.db import migrations, models
import objects.models.work_model


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_rename_work_workmodel_item_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='item_data',
            field=models.FileField(blank=True, help_text='Excel-file', null=True, upload_to=objects.models.work_model.WorkModel._work_path_, validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
    ]
