# Generated by Django 4.2.6 on 2023-10-16 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_alter_workmodel_item_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='work_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
