# Generated by Django 4.2.6 on 2023-10-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_workmodel_work_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatemodel',
            name='grade_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='grade_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='Z', max_length=2),
        ),
    ]
