# Generated by Django 4.2.6 on 2023-10-11 05:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_dictsecondnamemodel'),
        ('objects', '0003_disciplinemodel_disciplinemodel_teacher_title'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_set', to='dictionaries.dictfirstnamemodel')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_set', to='objects.groupmodel')),
                ('second_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_set', to='dictionaries.dictsecondnamemodel')),
            ],
        ),
    ]
